name: tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/easbarba/onur-rust:0.4.0

    defaults:
      run:
        working-directory: /home/easbarba/app

    steps:
      - name: Integration Tests

        run: |
          ./prepare.bash
          cargo test --verbose
